# Generated by Django 5.0.2 on 2024-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('type', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('volume', models.IntegerField()),
                ('genre', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('pages', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
