# Generated by Django 5.0.2 on 2024-02-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('views', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comixshop.genres')),
            ],
        ),
    ]
